// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysezpbbfgalmewpzqgws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZXpwYmJmZ2FsbWV3cHpxZ3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjExMjQsImV4cCI6MjA2ODQzNzEyNH0.oMPekzbPyAZ5zkCWvLbRRMI1Shttm5Q2K__POvznOvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});